config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  ### Registration & Login
  get '/register', to: 'app_auths#new'
  resources :app_auths, only: [:create]

  resources :users, only: [:new, :create, :show]

  get '/auth/google_oauth2/callback', to: 'google_auths#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  ### Public
  # Landmarks
  resources :landmarks, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :landmarks, only: [:index, :show]
    end
  end

  # Recordings
  resources :recordings, only: [:index]

  # Tours
  resources :tours, only: [:index, :show, :create]
  get '/tours/:tour_id/landmarks/:id', to: 'tour/landmarks#show', as: 'tour_landmark'

  ### User
  namespace :user do
    get '/dashboard', to: 'dashboard#index'
    delete '/dashboard/:id', to: 'recordings#destroy', as: :delete_recording
    get '/votes', to: 'votes#create'
    resources :landmarks, only: [:show] do
      resources :recordings, only: [:new, :create]
    end
    resources :flags, only: :create
  end

  # Tour list
  get '/tour_list', to: 'tour_list#show'
  delete '/tour_list', to: 'tour_list#destroy', as: :empty_tour_list
  namespace :tour_list do
    resources :landmarks, only: [:show, :create, :destroy] do
      resources :recordings, only: [:index, :new, :create, :destroy]
      post '/recordings/:id', to: 'recordings#update', as: :pick_recording
    end
  end

  ### Admin

  namespace :admin do
    get '/users/:user_id', to: 'users#show'
    delete '/destroy/:id', to: 'recordings#destroy', as: :delete_recording
  end
end

app/models/landmark.rb
class Landmark < ApplicationRecord
  include Votable
  
  has_many :recordings
  has_many :tours, through: :recordings

  validates_presence_of :lat, :long, :name, :address, :category, :photo_reference
  validates :place_id, presence: true, uniqueness: true

  before_save :update_md5_hash

  private

  def update_md5_hash
    self.md5_hash = Digest::MD5.hexdigest(
      "#{self.name}
      #{self.place_id}
      #{self.address}
      #{self.phone_number}
      #{self.category}
      #{self.website}"
    )
  end
end

app/controllers/api/v1/landmarks_controller.rb
class Api::V1::LandmarksController < ApplicationController

  def index
    render json: LandmarkSerializer.new(Landmark.all)
  end

  def show
    info = GoogleService.get_place_id(params[:id])
    render json: LandmarkSerializer.new(Landmark.find_by(place_id: info))
  end

end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  def index
    @tours = Tour.all
  end

  def show
    render locals: {
      facade: LandmarksShowFacade.new(params[:id])
    }
  end
end

app/controllers/tour/landmarks_controller.rb
class Tour::LandmarksController < ApplicationController
  def show
    render locals: {
      facade: TourLandmarkShowFacade.new(params[:id], params[:tour_id])
    }
  end
end

app/controllers/tour_list/landmark_controller.rb
class TourList::LandmarkController < TourList::BaseController
  def create
    landmark = Landmark.find(params[:id])
    unless tour_list.contents.keys.include?(landmark.id.to_s)
      tour_list.add_landmark(landmark.id)
      flash[:notice] = "You have added #{landmark.name} to your tour list."
      session[:tour_list] = tour_list.contents
      flash[:success] = "You have #{tour_list.total_count} landmarks in your tour list."
    else
      flash[:notice] = "You already have #{landmark.name} in your tour list."
    end

    redirect_to landmarks_path
  end

  def destroy
    landmark = Landmark.find(params[:id])
    tour_list.remove_landmark(landmark.id)
    session[:tour_list] = tour_list.contents
    flash[:success] = "#{landmark.name} has been removed from your tour list."

    redirect_to tour_list_path
  end
end

app/controllers/tour_list/landmarks_controller.rb
class TourList::LandmarksController < User::BaseController
  def create
    landmark = Landmark.find(params[:landmark_id])
    if tour_list.contents.keys.include?(landmark.id.to_s)
      flash[:danger] = "You already have #{landmark.name} in your tour list."
    else
      tour_list.add_landmark(landmark.id)
      session[:tour_list] = tour_list.contents
      flash[:success] = "You have added #{landmark.name} to your tour list. You have #{tour_list.total_count} landmark(s) in your tour list."
    end

    redirect_to landmarks_path
  end

  def destroy
    landmark = Landmark.find(params[:id])
    tour_list.remove_landmark(landmark.id)
    session[:tour_list] = tour_list.contents
    flash[:success] = "#{landmark.name} has been removed from your tour list."

    redirect_back fallback_location: tour_list_path
  end
end

app/views/landmarks/index.html.erb
<!doctype html>

<html lang="en">
<head>

  <style>
    #mapid { height: 500px; width: 100%};
  </style>
</head>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/leaflet-routing-machine.css"/>
<link rel="icon" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/leaflet.routing.icons.png"/>
<link rel="icon" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/routing-icon.png"/>
<link rel="icon" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/images/layers-2x.png"/>


<body>
<div id="mapid"></div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/leaflet-routing-machine.js">
</script>

<script>
//define button to add to map
  var locateButton = L.Control.extend({
    options: {
      position: 'topright'
    },
    onAdd: function (map) {
        var btn = document.createElement("BUTTON");
        btn.setAttribute('class', 'btn btn-primary')
        btn.innerHTML = "Use My Location"
        btn.setAttribute('onclick', "map.locate()")
        return btn;
      },
  });

   var greenIcon = new L.Icon({
     iconUrl: '<%= image_path('tree.png')%>',
     shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
     iconSize: [25, 41],
     iconAnchor: [12, 41],
     popupAnchor: [1, -34],
     shadowSize: [41, 41]
   });

   var greyIcon = new L.Icon({
     iconUrl: '<%= image_path('congress.png')%>',
     shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
     iconSize: [25, 41],
     iconAnchor: [12, 41],
     popupAnchor: [1, -34],
     shadowSize: [41, 41]
   });

   var violetIcon = new L.Icon({
     iconUrl: '<%= image_path('theater.png')%>',
     shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
     iconSize: [25, 41],
     iconAnchor: [12, 41],
     popupAnchor: [1, -34],
     shadowSize: [41, 41]
   });

   var orangeIcon = new L.Icon({
     iconUrl: '<%= image_path('cramschool.png')%>',
     shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
     iconSize: [25, 41],
     iconAnchor: [12, 41],
     popupAnchor: [1, -34],
     shadowSize: [41, 41]
   });

   var userIcon = new L.Icon({
     iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-blue.png',
     shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
     iconSize: [25, 41],
     iconAnchor: [12, 41],
     popupAnchor: [1, -34],
     shadowSize: [41, 41]
   });

function selectMarkerColor(category){
  if (category === 'park') {
    return greenIcon
  } else if (category ==='theater') {
    return violetIcon
  } else if (category ==='government'){
    return greyIcon
  } else {
    return orangeIcon
  }
};

//empty vars to make layers
var theaters = []
var museums = []
var parks = []
var governments = []

fetch('api/v1/landmarks')
.then(function(response) {
  return response.json();
})
.then(function(myJson) {
  //iterate over landmarks, make points
  myJson['data'].forEach(function(landmark){
    let marker = L.marker([landmark['attributes']['lat'], landmark['attributes']['long']],{
      icon: selectMarkerColor(landmark['attributes']['category'])
    });
  //add popups to landmarks
  let name = landmark['attributes']['name']
  let id = landmark['id']
    marker.bindPopup(name.link(`/landmarks/${id}`) + `<br><button class="location_button" onclick="navigateTo(${landmark['attributes']['lat']}, ${landmark['attributes']['long']})" >Directions</button>`)
  if (landmark['attributes']['category'] === 'theater') {theaters.push(marker)}
  if (landmark['attributes']['category'] === 'museum') {museums.push(marker)}
  if (landmark['attributes']['category'] === 'park') {parks.push(marker)}
  if (landmark['attributes']['category'] === 'government') {governments.push(marker)}
  });
})
//make layers for map
.then(function(response){
  var museumMarkers = L.layerGroup(museums)
  var theaterMarkers = L.layerGroup(theaters)
  var parkMarkers = L.layerGroup(parks)
  var governmentMarkers = L.layerGroup(governments)
  var allMarkers = L.layerGroup(museums.concat(theaters).concat(parks).concat(governments))
//Make overlay interface
  var overlayMaps = {
      "museums": museumMarkers,
      "theaters": theaterMarkers,
      "parks": parkMarkers,
      "government": governmentMarkers,
      "all": allMarkers
  };
//make map
   map = L.map('mapid',{layers: [museumMarkers, theaterMarkers, parkMarkers, governmentMarkers]}).setView([39.7392358, -104.990251], 15)
   map.addControl(new locateButton());
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
  maxZoom: 18,
  id: 'mapbox.streets',
  accessToken: '<%=ENV['MAPBOX_API_KEY']%>'
  }).addTo(map);
  map.on('locationerror', onLocationError);
  map.on('locationfound', onLocationFound);
  L.control.layers(overlayMaps).addTo(map);
});

//add my location popup When User clicks locate me
function onLocationFound(e) {
  map.setView(e.latlng, 17)
  var radius = e.accuracy;
  currentPosition = L.marker(e.latlng,{icon: userIcon}).addTo(map)
  .bindPopup("You are within " + radius + " meters from this point").openPopup();
}
//Display error if cannot find user
function onLocationError(e) {
  alert(e.message);
}

//Set route to null, allows us to change route
var routingControl = null
function navigateTo(lat,long){
  navigator.geolocation.getCurrentPosition(function(position) {
    var my_lat = position.coords.latitude;
    var my_lng = position.coords.longitude;
    if (routingControl){
      routingControl.setWaypoints([]);
      map.removeControl(routingControl);
      routingControl = null;
    }
 //draw line on map from mapbox/walking
    routingControl = L.Routing.control({
      waypoints: [
      L.latLng(my_lat, my_lng),
      L.latLng(lat, long)
      ],
      router: L.Routing.mapbox('<%=ENV['MAPBOX_API_KEY']%>',{profile: 'mapbox/cycling'}),
      createMarker: function() { return null; },
      lineOptions: { addWaypoints: false },
      collapsible: true
    })
    routingControl.addTo(map);
  });
}

function searchLandmark(){
  let input = document.getElementById('searchTerm').value
  fetch(`api/v1/landmarks/${input}`)
  .then(function(response) {
    return response.json();
  })
  .then(function(myJson) {
    if (myJson['data']===null){
      window.alert('Please try a different search')
    } else{
    map.flyTo([parseFloat(myJson['data']['attributes']['lat']),parseFloat(myJson['data']['attributes']['long'])], 18)
  }
  })
};

 </script>

</body>
</html>

app/views/landmarks/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%=facade.landmark.lat%>, <%=facade.landmark.long%>)
    });
  </script>
<% end %>

<div>
  <div>
    <div class='landmark-header'>
      <%= render partial: 'shared/voting_arrows', object: facade.landmark %>
      <h3 class='inline-block'><%= facade.landmark.name %></h3>
    </div>
    <section class="picture">
      <%= image_tag facade.picture, class: "img-fluid img", style: "display: block; margin-left: auto; margin-right: auto; width: 80%;" %>
    </section>
  </div>

  <div>
    <section class="attributes">
      <p><b>Address: </b> <%= facade.landmark.address %></p>
      <% if facade.landmark.phone_number.nil? %>
        <p><b>Phone: </b>Not Available</p>
      <% else %>
        <p><b>Phone: </b> <%= facade.landmark.phone_number %></p>
      <% end %>
      <% if facade.landmark.website.nil? %>
      <p><b>Website: </b>Not Available</p>
      <% else %>
        <p><b>Website: </b> <%= link_to facade.landmark.website, facade.landmark.website, :target => "_blank" %></p>
      <% end %>
      <p><b>Category: </b> <%= facade.landmark_category %></p>
      </div>
    </section>
  </div>

  <div class="add-tour-list">
    <% if current_user? %>
      <%= button_to "Add to tour list", tour_list_landmarks_path(landmark_id: facade.landmark.id), class: 'btn btn-primary' %>
    <% end %>
    <section class="add-recordings">
      <% if current_user %>
        <%= button_to "Upload new recording", new_user_landmark_recording_path(facade.landmark), method: :get, class: 'btn btn-primary' %>
      <% end %>
    </section>
  </div>

  <div>
    <section class="recordings">
      <% unless facade.landmark_recordings.empty? %>
        <br>
        <h4>Recordings</h4>
        <% facade.landmark_recordings.each do |recording, total_score| %>
          <!--  TODO: use total_score instead of API call for each recording -->
          <div class='recording-list'>
            <%= render partial: 'shared/voting_arrows', object: recording %>
            <div class='recording-box'>
              Title: <%= recording.title %><br>
              Creator: <%= link_to recording.user.display_name, user_path(recording.user) %>
              <%= render partial: 'shared/audio_player', object: recording %>
            </div>
          </div>
        <% end %>
      <% end %>
    </section>
  </div>

  <div>
    <section class="tours">
      <h4>Tours with this landmark</h4>
      <% if facade.landmark_tours.any? %>
        <% facade.landmark_tours.each do |tour, total_score| %>
          <!--  TODO: use total_score instead of API call for each tour -->
          <div class='tour-list'>
            <%= render partial: 'shared/voting_arrows', object: tour %>
            <div class='tour-box'>
              <%= link_to tour.title, tour_path(tour) %><br> Creator: <%= link_to tour.user.display_name, user_path(tour.user) %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>No tours include this landmark</p>
      <% end %>
    </section>
  </div>

  <div>
    <br>
    <section class="map">
      <div id="map"></div>
    </section>
  </div>
</div>