config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  ### Registration & Login
  get '/register', to: 'app_auths#new'
  resources :app_auths, only: [:create]

  resources :users, only: [:new, :create, :show]

  get '/auth/google_oauth2/callback', to: 'google_auths#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  ### Public
  # Landmarks
  resources :landmarks, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :landmarks, only: [:index, :show]
    end
  end

  # Recordings
  resources :recordings, only: [:index]

  # Tours
  resources :tours, only: [:index, :show, :create]
  get '/tours/:tour_id/landmarks/:id', to: 'tour/landmarks#show', as: 'tour_landmark'

  ### User
  namespace :user do
    get '/dashboard', to: 'dashboard#index'
    delete '/dashboard/:id', to: 'recordings#destroy', as: :delete_recording
    get '/votes', to: 'votes#create'
    resources :landmarks, only: [:show] do
      resources :recordings, only: [:new, :create]
    end
    resources :flags, only: :create
  end

  # Tour list
  get '/tour_list', to: 'tour_list#show'
  delete '/tour_list', to: 'tour_list#destroy', as: :empty_tour_list
  namespace :tour_list do
    resources :landmarks, only: [:show, :create, :destroy] do
      resources :recordings, only: [:index, :new, :create, :destroy]
      post '/recordings/:id', to: 'recordings#update', as: :pick_recording
    end
  end

  ### Admin

  namespace :admin do
    get '/users/:user_id', to: 'users#show'
    delete '/destroy/:id', to: 'recordings#destroy', as: :delete_recording
  end
end

app/views/shared/_audio_player.html.erb
<script src="ac_quicktime.js" type="text/javascript"></script>
<figure>
  <audio controls style="width:100%">
    <source src="<%= audio_player.url %>" type="audio/mp4">
    Your browser does not support the
    <code>audio</code> element.
    <script type="text/javascript">
      QT_WriteOBJECT(<%= audio_player.url %>);
    </script>
  </audio>
</figure>
<% if current_user%>
<%=button_to "⚑", user_flags_path, params: {recording_id: audio_player.id} %>
<% end %>
<style>
  audio::-internal-media-controls-download-button {
    display:none;
  }
  audio::-webkit-media-controls-enclosure {
    overflow:hidden;
  }
  audio::-webkit-media-controls-panel {
    width: calc(100% + 33px);
  }
</style>

app/views/shared/_flash.html.erb
<section id="flash">
  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>
</section>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="<%= landmarks_path %>">
    <img src="<%= image_path('oddio-logo-landscape.png')%>" id='navbar-brand-logo' class="d-inline-block align-top"">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= landmarks_path %>">Map <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= tours_path %>">Tours <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= recordings_path %>">Recordings <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">About</a>
      </li>
      <% if current_user %>
        <% if current_user? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_dashboard_path %>">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= tour_list_path %>">Create Tour (<%= tour_list.total_count %>)</a>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="<%= logout_path %>">Log Out</a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%= login_path %>">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= register_path %>">Register</a>
        </li>
      <% end %>
    </ul>

    <% if current_page?(landmarks_path) %>
      <input class="mr-sm-2" type="search" placeholder="Enter a Place" aria-label="Search" id='searchTerm'>
      <button class="btn btn-outline-dark my-2 my-sm-0" onclick='searchLandmark()'>Search</button>
    <% end %>
  </div>
</nav>

app/views/shared/_reqd_field_label.html.erb
<small class="form-text text-muted">
  Required
</small>

app/views/shared/_voting_arrows.html.erb
<div class='vote'>
  <% if current_user? %>
    <div class="vote-button upvote" id="<%= voting_arrows.class.to_s.downcase %>-<%= voting_arrows.id %>-up-vote">
      ▲
    </div>
  <% end %>
  <div class="total-score">
    <%= voting_arrows.total_score %>
  </div>
  <% if current_user? %>
    <div class="vote-button downvote" id="<%= voting_arrows.class.to_s.downcase %>-<%= voting_arrows.id %>-down-vote">
      ▼
    </div>
  <% end %>
</div>