config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  ### Registration & Login
  get '/register', to: 'app_auths#new'
  resources :app_auths, only: [:create]

  resources :users, only: [:new, :create, :show]

  get '/auth/google_oauth2/callback', to: 'google_auths#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  ### Public
  # Landmarks
  resources :landmarks, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :landmarks, only: [:index, :show]
    end
  end

  # Recordings
  resources :recordings, only: [:index]

  # Tours
  resources :tours, only: [:index, :show, :create]
  get '/tours/:tour_id/landmarks/:id', to: 'tour/landmarks#show', as: 'tour_landmark'

  ### User
  namespace :user do
    get '/dashboard', to: 'dashboard#index'
    delete '/dashboard/:id', to: 'recordings#destroy', as: :delete_recording
    get '/votes', to: 'votes#create'
    resources :landmarks, only: [:show] do
      resources :recordings, only: [:new, :create]
    end
    resources :flags, only: :create
  end

  # Tour list
  get '/tour_list', to: 'tour_list#show'
  delete '/tour_list', to: 'tour_list#destroy', as: :empty_tour_list
  namespace :tour_list do
    resources :landmarks, only: [:show, :create, :destroy] do
      resources :recordings, only: [:index, :new, :create, :destroy]
      post '/recordings/:id', to: 'recordings#update', as: :pick_recording
    end
  end

  ### Admin

  namespace :admin do
    get '/users/:user_id', to: 'users#show'
    delete '/destroy/:id', to: 'recordings#destroy', as: :delete_recording
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  include Votable

  belongs_to :user
  has_many :tour_recordings
  has_many :recordings, through: :tour_recordings
  has_many :landmarks, through: :recordings

  validates_presence_of :title

  def recordings_for_landmark(landmark)
    recordings.where(recordings: {landmark: landmark})
  end
end

app/controllers/tour/landmarks_controller.rb
class Tour::LandmarksController < ApplicationController
  def show
    render locals: {
      facade: TourLandmarkShowFacade.new(params[:id], params[:tour_id])
    }
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    collection = Tour.all
    @tours = Tour.sort('tour', collection)
  end

  def show
    @tour = Tour.find(params[:id])
  end

  def create
    if all_landmarks_have_recordings?
      tour = Tour.create(user_id: current_user.id, title: params[:tour][:title])

      tour_recording.contents.keys.each do |key|
        TourRecording.create(tour_id: tour.id, recording_id: key.to_i)
      end

      flash[:success] = "Your tour has been created."
      session[:tour_list] = nil
      session[:tour_recording] = nil
      redirect_to user_dashboard_path
    else
      flash[:danger] = "Make sure to add a recording to all landmarks."

      redirect_to tour_list_path
    end
  end

  private

  def all_landmarks_have_recordings?
    landmarks = tour_list.contents.keys.map {|landmark_id, quantity| landmark_id.to_i}
    recordings = tour_recording.contents.values
    Set.new(landmarks) == Set.new(recordings)
  end
end

app/views/tours/index.html.erb
<h3>All Tours</h3>
<% if @tours.any? %>
  <% @tours.each do |tour, total_score| %>
  <!--  TODO: use total_score instead of API call for each tour -->
    <div class='tour-list'>
      <%= render partial: 'shared/voting_arrows', object: tour %>
      <% if tour.landmarks.first %>
        <img src=<%= tour.landmarks.first.photo_reference %> alt="<%= tour.title %> thumbnail" class="tour-thumb">
      <% end %>
      <div class='tour-box'>
        <%= link_to tour.title, tour_path(tour), class: 'tour-info'%><br>
        Creator: <%= link_to tour.user.display_name, user_path(tour.user), class: 'tour-info' %><br>
      </div>
    </div>
  <% end %>
<% else %>
  <p>No tours added yet</p>
<% end %>

app/views/tours/show.html.erb
<head>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css"/>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/leaflet-routing-machine.css"/>
   <link rel="icon" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/leaflet.routing.icons.png"/>
   <link rel="icon" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/routing-icon.png"/>
   <link rel="icon" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/images/layers-2x.png"/>
  <style>
    #mapid { height: 500px; }
  </style>
</head>

<div class='tour-header'>
  <%= render partial: 'shared/voting_arrows', object: @tour %>
  <h3 class='inline-block'><%= @tour.title %></h3>
</div>
<h4>Recordings</h4>
<% @tour.recordings.each do |recording| %>
  <div class='recording-list'>
    <%= render partial: 'shared/voting_arrows', object: recording %>
    <div class='recording-box'>
      Title: <%= recording.title %><br>
      Landmark: <%= link_to recording.landmark.name, tour_landmark_path(@tour, recording.landmark) %><br>
      Creator: <%= link_to recording.user.display_name, user_path(recording.user) %>
      <%= render partial: 'shared/audio_player', object: recording %>
    </div>
  </div>
<% end %>

<div id="mapid"></div>

<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/leaflet-routing-machine.js">
</script>
  <script>
    var mymap = L.map('mapid').setView([<%= @tour.landmarks.first.lat %>, <%=@tour.landmarks.first.long%>], 13)
    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
    accessToken: '<%=ENV['MAPBOX_API_KEY']%>'
    }).addTo(mymap);

    // /tours/:tour_id/landmarks/:id

    
    <% @tour.landmarks.each do |landmark| %>
    L.marker([<%=landmark.lat%>, <%=landmark.long%> ]).bindPopup("<%=landmark.name %>".link(`/tours/<%= @tour.id %>/landmarks/<%= landmark.id %>`)).addTo(mymap)
    <% end %>

    routingControl = L.Routing.control({
      waypoints: [
      L.latLng(my_lat, my_lng),
      L.latLng(lat, long)
      ],
      router: L.Routing.mapbox('<%=ENV['MAPBOX_API_KEY']%>',{profile: 'mapbox/cycling'}),
      createMarker: function() { return null; },
      lineOptions: { addWaypoints: false },
      collapsible: true
    })
    routingControl.addTo(map);


  </script>