config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  ### Registration & Login
  get '/register', to: 'app_auths#new'
  resources :app_auths, only: [:create]

  resources :users, only: [:new, :create, :show]

  get '/auth/google_oauth2/callback', to: 'google_auths#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  ### Public
  # Landmarks
  resources :landmarks, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :landmarks, only: [:index, :show]
    end
  end

  # Recordings
  resources :recordings, only: [:index]

  # Tours
  resources :tours, only: [:index, :show, :create]
  get '/tours/:tour_id/landmarks/:id', to: 'tour/landmarks#show', as: 'tour_landmark'

  ### User
  namespace :user do
    get '/dashboard', to: 'dashboard#index'
    delete '/dashboard/:id', to: 'recordings#destroy', as: :delete_recording
    get '/votes', to: 'votes#create'
    resources :landmarks, only: [:show] do
      resources :recordings, only: [:new, :create]
    end
    resources :flags, only: :create
  end

  # Tour list
  get '/tour_list', to: 'tour_list#show'
  delete '/tour_list', to: 'tour_list#destroy', as: :empty_tour_list
  namespace :tour_list do
    resources :landmarks, only: [:show, :create, :destroy] do
      resources :recordings, only: [:index, :new, :create, :destroy]
      post '/recordings/:id', to: 'recordings#update', as: :pick_recording
    end
  end

  ### Admin

  namespace :admin do
    get '/users/:user_id', to: 'users#show'
    delete '/destroy/:id', to: 'recordings#destroy', as: :delete_recording
  end
end

app/models/landmark.rb
class Landmark < ApplicationRecord
  include Votable
  
  has_many :recordings
  has_many :tours, through: :recordings

  validates_presence_of :lat, :long, :name, :address, :category, :photo_reference
  validates :place_id, presence: true, uniqueness: true

  before_save :update_md5_hash

  private

  def update_md5_hash
    self.md5_hash = Digest::MD5.hexdigest(
      "#{self.name}
      #{self.place_id}
      #{self.address}
      #{self.phone_number}
      #{self.category}
      #{self.website}"
    )
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  include Votable

  belongs_to :user
  has_many :tour_recordings
  has_many :recordings, through: :tour_recordings
  has_many :landmarks, through: :recordings

  validates_presence_of :title

  def recordings_for_landmark(landmark)
    recordings.where(recordings: {landmark: landmark})
  end
end

app/controllers/api/v1/landmarks_controller.rb
class Api::V1::LandmarksController < ApplicationController

  def index
    render json: LandmarkSerializer.new(Landmark.all)
  end

  def show
    info = GoogleService.get_place_id(params[:id])
    render json: LandmarkSerializer.new(Landmark.find_by(place_id: info))
  end

end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  def index
    @tours = Tour.all
  end

  def show
    render locals: {
      facade: LandmarksShowFacade.new(params[:id])
    }
  end
end

app/controllers/tour/landmarks_controller.rb
class Tour::LandmarksController < ApplicationController
  def show
    render locals: {
      facade: TourLandmarkShowFacade.new(params[:id], params[:tour_id])
    }
  end
end

app/controllers/tour_list/landmark_controller.rb
class TourList::LandmarkController < TourList::BaseController
  def create
    landmark = Landmark.find(params[:id])
    unless tour_list.contents.keys.include?(landmark.id.to_s)
      tour_list.add_landmark(landmark.id)
      flash[:notice] = "You have added #{landmark.name} to your tour list."
      session[:tour_list] = tour_list.contents
      flash[:success] = "You have #{tour_list.total_count} landmarks in your tour list."
    else
      flash[:notice] = "You already have #{landmark.name} in your tour list."
    end

    redirect_to landmarks_path
  end

  def destroy
    landmark = Landmark.find(params[:id])
    tour_list.remove_landmark(landmark.id)
    session[:tour_list] = tour_list.contents
    flash[:success] = "#{landmark.name} has been removed from your tour list."

    redirect_to tour_list_path
  end
end

app/controllers/tour_list/landmarks_controller.rb
class TourList::LandmarksController < User::BaseController
  def create
    landmark = Landmark.find(params[:landmark_id])
    if tour_list.contents.keys.include?(landmark.id.to_s)
      flash[:danger] = "You already have #{landmark.name} in your tour list."
    else
      tour_list.add_landmark(landmark.id)
      session[:tour_list] = tour_list.contents
      flash[:success] = "You have added #{landmark.name} to your tour list. You have #{tour_list.total_count} landmark(s) in your tour list."
    end

    redirect_to landmarks_path
  end

  def destroy
    landmark = Landmark.find(params[:id])
    tour_list.remove_landmark(landmark.id)
    session[:tour_list] = tour_list.contents
    flash[:success] = "#{landmark.name} has been removed from your tour list."

    redirect_back fallback_location: tour_list_path
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    collection = Tour.all
    @tours = Tour.sort('tour', collection)
  end

  def show
    @tour = Tour.find(params[:id])
  end

  def create
    if all_landmarks_have_recordings?
      tour = Tour.create(user_id: current_user.id, title: params[:tour][:title])

      tour_recording.contents.keys.each do |key|
        TourRecording.create(tour_id: tour.id, recording_id: key.to_i)
      end

      flash[:success] = "Your tour has been created."
      session[:tour_list] = nil
      session[:tour_recording] = nil
      redirect_to user_dashboard_path
    else
      flash[:danger] = "Make sure to add a recording to all landmarks."

      redirect_to tour_list_path
    end
  end

  private

  def all_landmarks_have_recordings?
    landmarks = tour_list.contents.keys.map {|landmark_id, quantity| landmark_id.to_i}
    recordings = tour_recording.contents.values
    Set.new(landmarks) == Set.new(recordings)
  end
end

app/views/tour/landmarks/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%=facade.landmark.lat%>, <%=facade.landmark.long%>)
    });
  </script>
<% end %>

<div>
  <div>
    <div class='landmark-header'>
      <%= render partial: 'shared/voting_arrows', object: facade.landmark %>
      <h3 class='inline-block'><%= facade.landmark.name %></h3>
    </div>
    <section class="picture">
      <%= image_tag facade.picture, class: "img-fluid img", style: "display: block; margin-left: auto; margin-right: auto; width: 80%;" %>
    </section>
  </div>

  <div>
    <section class="attributes">
      <br>
      <p><b>Address: </b> <%= facade.landmark.address %></p>
      <% if facade.landmark.phone_number.nil? %>
        <b>Phone: </b>Not Available</p>
      <% else %>
        <p><b>Phone: </b> <%= facade.landmark.phone_number %></p>
      <% end %>
      <% if facade.landmark.website.nil? %>
        <b>Website: </b>Not Available</p>
      <% else %>
        <p><b>Website: </b> <%= link_to facade.landmark.website, facade.landmark.website, :target => "_blank" %></p>
      <% end %>
      <p><b>Category: </b> <%= facade.landmark.category.capitalize %></p>
    </section>
  </div>

  <div>
    <section class="add-recordings">
      <% if current_user %>
        <%= button_to "Upload new recording", new_user_landmark_recording_path(facade.landmark), method: :get, class: 'btn btn-primary' %>
      <% end %>
    </section>
  </div>

  <div>
    <section class="recordings">
      <% unless facade.recordings.empty? %>
        <br>
        <h4>Recordings for this tour (<%= link_to facade.tour.title, tour_path(facade.tour) %>)</h4>
        <% facade.recordings.each do |recording| %>
          <div class='recording-list'>
            <%= render partial: 'shared/voting_arrows', object: recording %>
            <div class='recording-box'>
              Title: <%= recording.title %><br>
              Creator: <%= link_to recording.user.display_name, user_path(recording.user) %>
              <%= render partial: 'shared/audio_player', object: recording %>
            </div>
          </div>
        <% end %>
        <%= link_to 'View all Recordings', landmark_path(facade.landmark), class: 'btn btn-primary' %>
      <% end %>
    </section>
  </div>

  <div>
    <br>
    <section class="map">
      <div id="map"></div>
    </section>
  </div>
</div>